version: '3.8'

services:
  rails-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    ports:
      - "3000:3000"

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: /workspaces/rails-interview/.devcontainer/start-sidekiq.sh
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    working_dir: /workspaces/rails-interview

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data: